---
# tasks file for Cambia_Propiedad_sanchez
---
# Rol 3: Cambia_Propiedad_sanchez

- name: Cambiar propietario de /UTN/Alumno
  ansible.builtin.file:
    path: "/UTN/Alumno"
    owner: Alumno
    group: GAlumnos
    state: directory

- name: Cambiar propietario de /UTN/Profesor
  ansible.builtin.file:
    path: "/UTN/Profesor"
    owner: Profesor
    group: GProfesores
    state: directory

